name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: cmglezpdev
          config_timezone: Cuba
          
          # General data about my Github 
          plugin_isocalendar: yes

          # Plugin for my top languages
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_ignored: Jupiter Notebook

          # Wakatime plugin
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages, languages-graph
          plugin_wakatime_days: 180
          
          plugin_leetcode: yes
          plugin_leetcode_user: cmglezpdev
          plugin_leetcode_sections: solved, skills, recent

          # Plugin code habits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          
          plugin_achievements: yes
          plugin_achievements_threshold: X
          
      
