name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: cmglezpdev
          config_timezone: Cuba
          
          plugin_isocalendar: yes
          
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          
          plugin_topics: yes
          plugin_topics_mode: icons
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, languages, languages-graph
          plugin_wakatime_days: 180
          
          plugin_leetcode: yes
          plugin_leetcode_user: cmglezpdev
          plugin_leetcode_sections: solved, skills, recent
          
          plugin_achievements: yes
          plugin_achievements_threshold: X
          
      
